---


- name: "Do repo directories exist"
  stat:
    path: "{{reporoot}}/{{ item.value.reposvr_repodir }}"
  with_dict: "{{REPOS}}"
  register: "repodirs"

- name: "Create missing repo directories"
  file:
    path: "{{reporoot}}/{{ item.item.value.reposvr_repodir }}"
    state: directory
  with_items: "{{ repodirs.results }}"
  when: item.stat.exists == false

- name: "Copy Files to each repo location"
  get_url:
    url: "{{ item.value.reposvr_webloc }}/{{ item.value.reposvr_filename }}"
    dest: "{{reporoot}}/{{ item.value.reposvr_repodir }}"
    mode: '0755'
  with_dict: "{{REPOS}}"
  when: 
    - "item.value.reposvr_useweb == 'yes'"

- name: "Extract Downloaded zip file for Satellite 6_6 workaround"
  unarchive:
    src: "{{reporoot}}/{{ item.value.reposvr_repodir }}/{{ item.value.reposvr_filename }}"
    dest: "{{reporoot}}/{{ item.value.reposvr_repodir }}"
    remote_src: yes
  with_dict: "{{REPOS}}"
  when: 
    - "item.value.reposvr_useweb == 'yes'"
    - "item.value.reposvr_filetype == 'archive'"
