---

- name: "Package installation"
  yum: 
    name: "{{ item }}"
  loop: "{{PACKAGES}}"

- name: "Check if main repository directory exists"
  stat:
    path: "{{ reporoot }}"
  register: repospath

- name: "Creates repo root directory if missing"
  file:
    path: "{{reporoot}}"
    state: directory
  when: 
    - repospath.stat.exists == false

- name: 'Ensure firewalld is running'
  service:
    name: firewalld
    state: started
    enabled: yes

- name: 'Open Firewall for repo use'
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{FIREWALL_SERVICES}}"




